//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewYear2020.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ISChou = false;
        }
    
        public int ID { get; set; }
        public string OpenID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string JobID { get; set; }
        public string Address { get; set; }
        public Nullable<int> PrizeID { get; set; }
        public int c1snf { get; set; }
        public int c2snm { get; set; }
        public int c3snq { get; set; }
        public int c4snl { get; set; }
        public int c5snt { get; set; }
        public int c6zzk { get; set; }
        public string aiqiyiKey { get; set; }
        public Nullable<System.DateTime> GetPrizeTime { get; set; }
        public string WeChatNickName { get; set; }
        public string HeadIMG { get; set; }
        public bool ISChou { get; set; }
    
        public virtual PrizeList PrizeList { get; set; }
    }
}
